# All basics services are here, remove that you will not use

version: '3'

services:
  api:
    build: 
      context: ./
      dockerfile: ./Dockerfile
      args: PORT=${PORT}
      ports: 
        - ${PORT}:${PORT}
      depends_on: 
        - redis
        - mongo
        - postgres
        - mysql
      environment: 
        - DEBUG=1
      env_file: ./.env

  mongo:
    container_name: mongodb
    image: mongo:4.0.22
    volumes: 
      - ./data/mongo:/data/db
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    env_file: ./.env

  redis:
    container_name: redisdb
    image: bitnami/redis:5.0.13
    volumes: 
      - ./data/redis:/bitnami/redis/data
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_REPLICATION_MODE: master
    expose: 
      - ${REDIS_PORT}
    env_file: ./.env

  postgres:
    container_name: postgresdb
    image: postgres:9.6.23
    volumes: 
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - ${PSQL_PORT}:${PSQL_PORT}
    environment:
      POSTGRES_MULTIPLE_DATABASES: ${DB_NAME}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_USER: ${PSQL_USER}
    env_file: ./.env

  mysql:
    container_name: mysqldb
    image: mysql:5.7
    environment:
      DB_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_SECRET: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    env_file: ./.env      
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}

volumes: 
  data:
