# All basics services are here, remove that you will not use

version: '3'

services:
  mysql:
    container_name: mysqldb
    image: mysql:5.7
    environment:
      DB_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_SECRET: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    env_file: ./.env      
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}

volumes: 
  data:
